# Generated by Django 5.2.18 on 2026-10-09 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_key', models.CharField(max_length=100)),
                ('section_name', models.CharField(help_text='Human-friendly label in admin editor', max_length=150)),
                ('badge_text', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('media_url', models.URLField(blank=True, default='', max_length=500)),
                ('primary_btn_text', models.CharField(blank=True, default='', max_length=100)),
                ('primary_btn_link', models.CharField(blank=True, default='', max_length=255)),
                ('secondary_btn_text', models.CharField(blank=True, default='', max_length=100)),
                ('secondary_btn_link', models.CharField(blank=True, default='', max_length=255)),
                ('json_data', models.JSONField(blank=True, default=dict)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.page')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('page', 'section_key')},
            },
        ),
    ]
