# Generated by Django 5.1.15 on 2026-10-10 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(default='Technology', max_length=100)),
                ('excerpt', models.TextField(help_text='Short teaser paragraph for cards and SEO')),
                ('content', models.TextField(help_text='Full markdown or HTML content')),
                ('cover_image', models.URLField(blank=True, default='', max_length=500)),
                ('author_name', models.CharField(default='Prajnadhara Faculty', max_length=150)),
                ('author_avatar', models.URLField(blank=True, default='', max_length=500)),
                ('author_role', models.CharField(blank=True, default='Lead Instructor', max_length=150)),
                ('read_time', models.CharField(default='5 min read', max_length=50)),
                ('views_count', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('category_rel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='cms.blogcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
