# Generated by Django 5.2.18 on 2026-10-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon_code', models.CharField(blank=True, default='', max_length=50)),
                ('payment_method', models.CharField(default='card', max_length=50)),
                ('payment_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='completed', max_length=30)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course_title', models.CharField(max_length=255)),
                ('thumbnail', models.URLField(max_length=500)),
                ('instructor_name', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
