# Generated by Django 5.2.18 on 2026-10-09 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending Verification'), ('success', 'Success'), ('failed', 'Failed')], default='initiated', max_length=30)),
                ('gateway_provider', models.CharField(default='toucanpay', max_length=50)),
                ('terminal_id', models.CharField(blank=True, default='', max_length=50)),
                ('session_redirect_url', models.TextField(blank=True, default='')),
                ('rrn', models.CharField(blank=True, default='', max_length=100)),
                ('txn_id', models.CharField(blank=True, default='', max_length=150)),
                ('psp_ref_no', models.CharField(blank=True, default='', max_length=150)),
                ('approval_code', models.CharField(blank=True, default='', max_length=100)),
                ('action_code', models.CharField(blank=True, default='', max_length=50)),
                ('payer_vpa', models.CharField(blank=True, default='', max_length=150)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
