# Generated by Django 5.2.18 on 2026-10-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='global', max_length=100, unique=True)),
                ('platform_name', models.CharField(default='Prajnadhara EDU', max_length=150)),
                ('support_email', models.EmailField(default='support@prajnadhara.edu', max_length=254)),
                ('instructor_revenue_share_percent', models.IntegerField(default=70)),
                ('platform_fee_percent', models.IntegerField(default=30)),
                ('gst_rate_percent', models.IntegerField(default=18)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('auto_approve_instructors', models.BooleanField(default=False)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
