# Generated by Django 5.2.18 on 2026-10-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_governance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='global', max_length=100, unique=True)),
                ('host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('port', models.IntegerField(default=587)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('from_email', models.EmailField(default='noreply@prajnadhara.edu', max_length=254)),
                ('sender_name', models.CharField(default='Prajnadhara EDU', max_length=150)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('send_welcome_email', models.BooleanField(default=True)),
                ('send_purchase_receipt', models.BooleanField(default=True)),
                ('send_course_updates', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'SMTP Settings',
            },
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='allow_instructor_registration',
            field=models.BooleanField(default=False),
        ),
    ]
