# Generated by Django 5.2.18 on 2026-10-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_governance', '0002_smtpsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='toucanpay', max_length=100, unique=True)),
                ('provider_name', models.CharField(default='ToucanPay', max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('environment', models.CharField(choices=[('uat', 'UAT / Sandbox'), ('production', 'Production')], default='uat', max_length=20)),
                ('merchant_name', models.CharField(default='Prajnadhara Learning Platform', max_length=255)),
                ('login_id', models.CharField(blank=True, default='', max_length=100)),
                ('mid', models.CharField(blank=True, default='', max_length=100)),
                ('tid', models.CharField(blank=True, default='', max_length=100)),
                ('password', models.CharField(blank=True, default='', max_length=500)),
                ('mac_token', models.TextField(blank=True, default='')),
                ('api_endpoint_uat', models.CharField(default='https://pay.testtoucanpay.in/api/auth/getpaymentsession', max_length=255)),
                ('api_endpoint_prod', models.CharField(default='https://pay.toucanpay.in/api/auth/getpaymentsession', max_length=255)),
                ('status_check_endpoint_uat', models.CharField(default='https://pay.testtoucanpay.in/api/pay/v1/checkStatus', max_length=255)),
                ('status_check_endpoint_prod', models.CharField(default='https://pay.toucanpay.in/api/pay/v1/checkStatus', max_length=255)),
                ('merchant_portal_url', models.CharField(default='https://merchant.testtoucanpay.in', max_length=255)),
                ('merchant_region_url', models.CharField(default='https://merchant.testtoucanpay.in/', max_length=255)),
                ('success_url', models.CharField(default='http://localhost:3000/order-confirmation', max_length=255)),
                ('failure_url', models.CharField(default='http://localhost:3000/checkout?status=failed', max_length=255)),
                ('callback_url', models.CharField(default='http://localhost:8000/api/payments/toucan/callback/', max_length=255)),
                ('whitelisted_ip', models.CharField(blank=True, default='', max_length=100)),
                ('allow_sandbox_simulation_on_timeout', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Payment Gateway Settings',
            },
        ),
    ]
