# Generated by Django 5.2.18 on 2026-10-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_governance', '0002_smtpsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='toucanpay', max_length=100, unique=True)),
                ('provider_name', models.CharField(default='ToucanPay', max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('environment', models.CharField(choices=[('uat', 'UAT / Sandbox'), ('production', 'Production')], default='uat', max_length=20)),
                ('merchant_name', models.CharField(default='Prajnadhara Infotech Private Limited', max_length=255)),
                ('login_id', models.CharField(default='prajnadhar', max_length=100)),
                ('mid', models.CharField(default='962042872713381', max_length=100)),
                ('tid', models.CharField(default='78183008', max_length=100)),
                ('password', models.CharField(default='Password@123', max_length=255)),
                ('mac_token', models.TextField(default='eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJzZWxmc2VydmVAcHJham5hMDQyNiIsImlhdCI6MTc5MTQ1NDk0OCwiZXhwIjoxOTE3NjA4NDAwfQ.MaSaXcIT6hlcPfcIMZfYmAKLgrc6VJFMmW6aqkLkuWWhFCo65lbD4fxnddN8UnRNIGEX-Ehd2UWQi0eRobqTMY6k4jnmUICAo0bli1tML0BGlUfNjEXuhcDLbzNwSfmYfhve4gOgO_PRsKuHMkP91ZjEm0xsYAFiYQP8s7EOGdh55RBLAkWtfs666rqmzKJ2zowIvbu-xIy3EBbKZ-fBwUkaHEJOplx4SG_pYNXoXqKhyifH6cZPyswm2d8TzNfSdYdu_JIOaRTZcpZo7iy0x3gTrlhtSIMM4woYUhPRE3xWPtwAGpRWptBgvIC-IWBCvRK7QDZ3JtyfmJDK-SB1tg')),
                ('api_endpoint_uat', models.CharField(default='https://pay.testtoucanpay.in/api/auth/getpaymentsession', max_length=255)),
                ('api_endpoint_prod', models.CharField(default='https://pay.toucanpay.in/api/auth/getpaymentsession', max_length=255)),
                ('status_check_endpoint_uat', models.CharField(default='https://pay.testtoucanpay.in/api/pay/v1/checkStatus', max_length=255)),
                ('status_check_endpoint_prod', models.CharField(default='https://pay.toucanpay.in/api/pay/v1/checkStatus', max_length=255)),
                ('merchant_portal_url', models.CharField(default='https://merchant.testtoucanpay.in', max_length=255)),
                ('merchant_region_url', models.CharField(default='https://merchant.testtoucanpay.in/', max_length=255)),
                ('success_url', models.CharField(default='http://localhost:3000/order-confirmation', max_length=255)),
                ('failure_url', models.CharField(default='http://localhost:3000/checkout?status=failed', max_length=255)),
                ('callback_url', models.CharField(default='http://localhost:8000/api/payments/toucan/callback/', max_length=255)),
                ('whitelisted_ip', models.CharField(default='117.99.201.162', max_length=100)),
                ('allow_sandbox_simulation_on_timeout', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Gateway Settings',
            },
        ),
    ]
