# Generated by Django 5.2.18 on 2026-10-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_governance', '0003_paymentgatewaysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgatewaysettings',
            name='allow_sandbox_simulation_on_timeout',
            field=models.BooleanField(default=False),
        ),
    ]
