# Generated by Django 5.2.18 on 2026-10-10 09:00

import apps.core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_governance', '0004_alter_paymentgatewaysettings_allow_sandbox_simulation_on_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgatewaysettings',
            name='mac_token',
            field=apps.core.encryption.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paymentgatewaysettings',
            name='password',
            field=apps.core.encryption.EncryptedCharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='password',
            field=apps.core.encryption.EncryptedCharField(blank=True, default='', max_length=500),
        ),
    ]
