# Generated by Django 5.1.15 on 2026-10-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_governance', '0005_alter_paymentgatewaysettings_mac_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='favicon_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='logo_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='site_title',
            field=models.CharField(default='Prajnadhara EDU', max_length=200),
        ),
    ]
