# Generated by Django 5.2.18 on 2026-10-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='semester',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
